### ISSUE TITLE
Features broken due to encryption.

### ISSUE THREAD

**Issue by admiralspeedy** [Quackster/Havana#47]
1. Infobus park does not load, just sits on a black screen.
2. Clicking the ticket machines does nothing.

Reverting the encryption commit fixes both issues. I am not sure how the encryption could possibly impact the ability for the ticket machines to work properly since clicking them doesn't even send a packet to the server.

**Comment by Quackster** [comment]
Fixed not being able to enter park_a. The offending line was [here](https://github.com/Quackster/Havana/blob/master/Havana-Server/src/main/java/org/alexdev/havana/messages/incoming/rooms/G_USRS.java#L26).

Commit which fixed it: https://github.com/Quackster/Havana/commit/42c811700bf0175f9f34d272f403e6f0faada37a

Fixed no ticket window showing - was due to using hh_entry_init.cct from DCR Project's release 31 client files but I suspect that Bifi2000 reused files because by all intents and purposes the ticket window should work, yet it was intentionally disabled by Sulake in that specific hh_entry_init.cct. 

I solved it by using hh_entry_init.cct from release 29.

Commit which fixed it: https://github.com/Quackster/Havana/commit/c5490b8161fd4f8e81b4418c38d333175359a0e1
